set(CMAKE_SYSTEM_NAME Windows CACHE INTERNAL "" FORCE)

set(CMAKE_GENERATOR_PLATFORM Win32 CACHE INTERNAL "" FORCE)
set(CMAKE_BUILD_TYPE Debug CACHE INTERNAL "" FORCE)
set(CMAKE_GENERATOR "Visual Studio 16 2019" CACHE INTERNAL "" FORCE)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/lib/${CMAKE_BUILD_TYPE}/${CMAKE_GENERATOR_PLATFORM}/ CACHE INTERNAL "" FORCE) 
