/* date = May 5th 2021 4:12 pm */

#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

// NOTE(Momo): Global Settings
#define GAME_DESIGN_WIDTH 800
#define GAME_DESIGN_HEIGHT 800
#define Game_DesignDepth 200

#define GAME_AUDIO_SAMPLES_PER_SECOND 48000
#define GAME_AUDIO_CHANNELS 2
#define GAME_AUDIO_BITS_PER_SAMPLE 16
#define GAME_AUDIO_LATENCY_FRAMES 1


#define GAME_ASSET_FILENAME "yuu"
#define GAME_ASSET_FILE_SIGNATURE "MOMO"

#endif //GAME_CONFIG_H
